INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Jennifer Quiteria', '111-1111', CURRENT_DATE);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Amelia Amarilis', '111-1112', CURRENT_DATE - 1);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Arleth Salvador', '111-1113', CURRENT_DATE - 2);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Andres Felipe', '111-1114', CURRENT_DATE - 3);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Jesica Augusto', '111-1115', CURRENT_DATE - 4);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Luisita Sandalio', '111-1116', CURRENT_DATE - 5);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Custodia Carmelo', '111-1117', CURRENT_DATE - 6);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Yamila Fidelia', '111-1118', CURRENT_DATE - 7);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Jhon Celestino', '111-1119', CURRENT_DATE - 8);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Roman Placido', '111-1120', CURRENT_DATE - 9);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Ernestina Arturo', '111-1121', CURRENT_DATE - 10);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Lujan Amador', '111-1122', CURRENT_DATE - 11);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Ileana Rogelio', '111-1123', CURRENT_DATE - 12);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Marisa Encarna', '111-1124', CURRENT_DATE - 13);
INSERT INTO Adopter (name, phone, date_adoption) VALUES ('Mara Albino', '111-1125', CURRENT_DATE - 14);

INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('CAT', 'Fuchsia', 'Aegean', 1);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('CAT', 'Alsha', 'Bengal', 2);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('CAT', 'Kobe', 'Bombay', 3);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('CAT', 'Newton', 'Cyprus', 4);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('CAT', 'Omen', 'Himalayan', 5);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('DOG', 'Valentina', 'Beagle', 6);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('DOG', 'Kayle', 'Akita', 7);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('DOG', 'Siri', 'Chihuahua', 8);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('DOG', 'Aster', 'Chow Chow', 9);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('DOG', 'Maiki', 'Georgian Shepherd', 10);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('TURTLE', 'Q-ball', 'Red-Eared Slider', 11);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('TURTLE', 'Acadia', 'African Sideneck Turtle', 12);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('TURTLE', 'Sonny', 'Eastern Box Turtle', 13);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('TURTLE', 'Skye', 'Western Painted Turtle', 14);
INSERT INTO Animal (type_pet, pet_name, pet_breed, adopter_id) VALUES ('TURTLE', 'Danu', 'Common Musk Turtle', 15);
